//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTurn_Model
{
    using System;
    
    public enum AppStatus : int
    {
        Submitted = 1,
        Reviewing = 2,
        Interview = 3,
        Hired = 4,
        Declined = 5
    }
}
