//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTurn_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationID { get; set; }
        public int DegreeID { get; set; }
        public int StudentID { get; set; }
        public int DateReceived { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Student Student { get; set; }
    }
}
