//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTurn_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int EmployeeID { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public int JobPostingID { get; set; }
        public Nullable<MidTerm> MidtermExam { get; set; }
        public Nullable<Final> FinalExam { get; set; }
    
        public virtual JobPosting JobPosting { get; set; }
        public virtual Student Student { get; set; }
        public virtual Faculty Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
