//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InTurn_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MajorRequirement
    {
        public int MajorRequirementID { get; set; }
        public int MajorID { get; set; }
        public int JobPostingID { get; set; }
    
        public virtual JobPosting JobPosting { get; set; }
        public virtual Major Major { get; set; }
    }
}
